# Generated by Django 5.2.6 on 2026-06-09 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(default='synced', max_length=20)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
                ('sync_status', models.CharField(default='pending', max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_datos.empresa')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_nfactura', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('numero_factura', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField()),
                ('total', models.FloatField()),
                ('tipo', models.CharField(choices=[('COMPRA', 'Compra'), ('VENTA', 'Venta')], max_length=10)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(default='pending', max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_datos.empresa')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'factura',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('rut', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('numero_contacto', models.CharField(blank=True, max_length=30, null=True)),
                ('forma_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('foto_url', models.URLField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(default='pending', max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_datos.empresa')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id_articulo', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('nombre_articulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_qr', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_barra', models.CharField(blank=True, max_length=100, null=True)),
                ('precio_compra', models.FloatField()),
                ('precio_venta', models.FloatField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('foto_url', models.URLField(blank=True, null=True)),
                ('unidad_medida', models.CharField(choices=[('unidad', 'Unidad'), ('kg', 'Kilogramo'), ('lb', 'Libra')], default='unidad', max_length=10)),
                ('margen_ganancia', models.FloatField(default=0.0)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(default='pending', max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_datos.empresa')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_datos.proveedor')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'db_table': 'articulo',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_usuario', models.CharField(max_length=20)),
                ('id_categorias', models.JSONField(default=list)),
                ('vistas', models.JSONField(default=list)),
                ('seccion', models.CharField(blank=True, max_length=100, null=True)),
                ('foto_url', models.URLField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(default='synced', max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_datos.empresa')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id_stock', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10)),
                ('unidades', models.IntegerField()),
                ('precio_unitario_compra', models.FloatField()),
                ('precio_unitario_venta', models.FloatField()),
                ('total', models.FloatField()),
                ('id_lote', models.CharField(blank=True, max_length=36, null=True)),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField()),
                ('sync_status', models.CharField(default='pending', max_length=20)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_datos.articulo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_datos.empresa')),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_datos.factura')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_datos.usuario')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'db_table': 'stock',
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_datos.usuario'),
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id_configuracion', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('nombre_app', models.CharField(blank=True, max_length=100, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('color_primario', models.CharField(default='#8B0000', max_length=9)),
                ('color_secundario', models.CharField(blank=True, max_length=9, null=True)),
                ('color_acento', models.CharField(blank=True, max_length=9, null=True)),
                ('color_texto', models.CharField(blank=True, max_length=9, null=True)),
                ('color_fondo', models.CharField(blank=True, max_length=9, null=True)),
                ('modo_oscuro', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(default='pending', max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_datos.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_datos.usuario')),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuraciones',
                'db_table': 'configuracion',
            },
        ),
    ]
