# Generated by Django 5.2.6 on 2026-06-11 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_datos', '0002_plan_empresa_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-fecha_hora'], 'verbose_name': 'Movimiento de stock', 'verbose_name_plural': 'Movimientos de stock'},
        ),
        migrations.AlterField(
            model_name='articulo',
            name='categoria',
            field=models.ForeignKey(blank=True, db_column='categoria', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos', to='base_datos.categoria'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='base_datos.articulo'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas', to='base_datos.factura'),
        ),
    ]
