# Generated by Django 5.2.6 on 2026-07-09 01:36
#
# Migración SOLO DE ESTADO (SeparateDatabaseAndState):
# estas columnas ya fueron creadas directamente en Supabase por la app móvil,
# así que aquí solo se actualiza el estado interno de Django sin ejecutar
# ningún ALTER TABLE. `python manage.py migrate` la registra sin tocar la BD.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_datos', '0003_alter_stock_options_alter_articulo_categoria_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='articulo',
                    name='cantidad_minima_mayor',
                    field=models.FloatField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='articulo',
                    name='es_mayorista',
                    field=models.BooleanField(blank=True, default=False, null=True),
                ),
                migrations.AddField(
                    model_name='articulo',
                    name='margen_ganancia_mayor',
                    field=models.FloatField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='articulo',
                    name='precio_compra_mayor',
                    field=models.FloatField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='articulo',
                    name='precio_venta_mayor',
                    field=models.FloatField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='usuario',
                    name='auth_id',
                    field=models.UUIDField(blank=True, null=True),
                ),
                migrations.AlterField(
                    model_name='usuario',
                    name='empresa',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_datos.empresa'),
                ),
                migrations.AlterField(
                    model_name='usuario',
                    name='id_categorias',
                    field=models.JSONField(blank=True, default=list, null=True),
                ),
                migrations.AlterField(
                    model_name='usuario',
                    name='vistas',
                    field=models.JSONField(blank=True, default=list, null=True),
                ),
            ],
        ),
    ]
