# Generated by Django 5.2.6 on 2026-07-09 10:25
#
# Migración SOLO DE ESTADO: la tabla configuracion_web se crea directamente
# en Supabase con el SQL Editor (ver README o la query en el repo de docs),
# igual que el resto de tablas gestionadas externamente. Django solo
# registra el modelo, sin ejecutar CREATE TABLE.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_datos', '0004_articulo_cantidad_minima_mayor_articulo_es_mayorista_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='ConfiguracionWeb',
                    fields=[
                        ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='config_web', serialize=False, to='base_datos.empresa')),
                        ('color_primario', models.CharField(default='#2563eb', max_length=9)),
                        ('color_acento', models.CharField(default='#f5c211', max_length=9)),
                        ('color_fondo', models.CharField(default='#f4f7fb', max_length=9)),
                        ('color_sidebar', models.CharField(default='#ffffff', max_length=9)),
                        ('color_texto', models.CharField(default='#0f1f33', max_length=9)),
                        ('logo_url', models.URLField(blank=True, null=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'verbose_name': 'Configuración web',
                        'verbose_name_plural': 'Configuraciones web',
                        'db_table': 'configuracion_web',
                    },
                ),
            ],
        ),
    ]
