# Generated by Django 5.2.6 on 2026-07-09 10:53
#
# Migración SOLO DE ESTADO: la columna foto_url ya existe en la tabla
# empresa de Supabase (la usa la app móvil para el logo del negocio).
# Solo se actualiza el estado interno de Django, sin ALTER TABLE.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_datos', '0005_configuracionweb'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='empresa',
                    name='foto_url',
                    field=models.URLField(blank=True, null=True),
                ),
            ],
        ),
    ]
