# Generated by Django 5.2.6 on 2026-07-09 20:32
#
# Migración SOLO DE ESTADO: la columna stock_minimo ya fue creada
# directamente en Supabase con:
#   ALTER TABLE public.articulo ADD COLUMN IF NOT EXISTS stock_minimo double precision;
# Solo se actualiza el estado interno de Django, sin ALTER TABLE.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_datos', '0006_empresa_foto_url'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='articulo',
                    name='stock_minimo',
                    field=models.FloatField(blank=True, null=True),
                ),
            ],
        ),
    ]
