# Generated by Django 5.2.6 on 2026-07-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_datos', '0007_articulo_stock_minimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='tipo',
            field=models.CharField(choices=[('COMPRA', 'Compra'), ('VENTA', 'Venta'), ('MERMA', 'Merma')], max_length=10),
        ),
    ]
