# Generated by Django 5.2.6 on 2026-08-09 10:07

import base_datos.models.pago.pago
import base_datos.models.pago.solicitud_premium
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_datos', '0008_alter_factura_tipo'),
    ]

    operations = [
        # NOTA: `articulo.precio_compra_mayor` quedó fuera a propósito. Se borró
        # del modelo sin migrar (drift previo a este cambio) y el autodetector lo
        # arrastraba aquí. Eliminar esa columna borra datos en producción, así que
        # es una decisión aparte y necesita su propia migración.
        migrations.RemoveField(
            model_name='empresa',
            name='fecha_pago',
        ),
        migrations.AddField(
            model_name='empresa',
            name='descuento_porcentaje',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='estado_suscripcion',
            field=models.CharField(choices=[('GRATUITO', 'Plan gratuito'), ('ACTIVA', 'Activa'), ('GRACIA', 'En periodo de gracia'), ('VENCIDA', 'Vencida')], default='GRATUITO', max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_vencimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='giro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='razon_social',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.CharField(default=base_datos.models.pago.pago._nuevo_id, max_length=36, primary_key=True, serialize=False)),
                ('usuarios_cobrados', models.IntegerField(default=1)),
                ('monto_neto', models.IntegerField(default=0)),
                ('monto_iva', models.IntegerField(default=0)),
                ('monto_total', models.IntegerField(default=0)),
                ('monto_descuento', models.IntegerField(default=0)),
                ('descripcion_descuento', models.CharField(blank=True, max_length=255, null=True)),
                ('metodo_pago', models.CharField(choices=[('TRANSFERENCIA', 'Transferencia'), ('FLOW', 'Flow')], default='TRANSFERENCIA', max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('RECHAZADO', 'Rechazado'), ('REEMBOLSADO', 'Reembolsado')], default='PENDIENTE', max_length=20)),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha_pago', models.DateTimeField()),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('periodo_inicio', models.DateTimeField(blank=True, null=True)),
                ('periodo_fin', models.DateTimeField(blank=True, null=True)),
                ('comprobante_url', models.URLField(blank=True, null=True)),
                ('comision_neto', models.IntegerField(blank=True, null=True)),
                ('comision_iva', models.IntegerField(blank=True, null=True)),
                ('comision_total', models.IntegerField(blank=True, null=True)),
                ('monto_abonado', models.IntegerField(blank=True, null=True)),
                ('fecha_abono', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_confirmados', to='base_datos.usuario')),
                ('empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='base_datos.empresa')),
                ('plan', models.ForeignKey(blank=True, db_column='id_plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='base_datos.plan')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pago',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudPremium',
            fields=[
                ('id_solicitud', models.CharField(default=base_datos.models.pago.solicitud_premium._nuevo_id, max_length=36, primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONTACTADO', 'Contactado'), ('CONVERTIDA', 'Convertida'), ('DESCARTADA', 'Descartada')], default='PENDIENTE', max_length=20)),
                ('nota', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_premium', to='base_datos.empresa')),
                ('pago', models.ForeignKey(blank=True, db_column='id_pago', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='base_datos.pago')),
                ('plan', models.ForeignKey(blank=True, db_column='id_plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='base_datos.plan')),
            ],
            options={
                'verbose_name': 'Solicitud de premium',
                'verbose_name_plural': 'Solicitudes de premium',
                'db_table': 'solicitud_premium',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['empresa', 'estado'], name='pago_id_empr_0b4d08_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudpremium',
            index=models.Index(fields=['estado', 'fecha_solicitud'], name='solicitud_p_estado_254a6e_idx'),
        ),
    ]
