# Generated by Django 5.2.6 on 2026-08-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_datos', '0009_pago_solicitudpremium_suscripcion_empresa'),
    ]

    operations = [
        # NOTA: `articulo.precio_compra_mayor` queda fuera otra vez a propósito.
        # Se borró del modelo sin migrar y el autodetector lo sigue arrastrando.
        # Esa columna existe en Supabase (la creó la app móvil, la migración 0004
        # es solo de estado), así que eliminarla borra datos y necesita su propia
        # decisión.
        migrations.AddField(
            model_name='usuario',
            name='vistas_web',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
